### ISSUE TITLE
Make is clearer that is project is deprecated.

### ISSUE THREAD

**Issue by steren** [bazelbuild/deprecated-dash#26]
We have "Warning: This project was experimental. It is not maintained anymore and should be considered deprecated." at the top of the README. But it does not seem enough.

We should:
P0: update the repo description to say DEPRECATED
P1: explore ways to 'archive' the repo. for example by using a new empty default branch that says deprecated and points to the current master branch

**Comment by MarkusTeufelberger** [comment]
Maybe consider opening a second organization on Github named "bazelbuild-deprecated" and move the repository there?

**Comment by damienmg** [comment]
Creating organization are pretty complex for us, we will just move the repo to be an attic and rename the branch to the new repo.

**Comment by steren** [comment]
Add also a 'deprecated' prefix to the repo description

**Comment by MarkusTeufelberger** [comment]
And rename the project, similar to buildtools/buildifier

**Comment by damienmg** [comment]
Closing and locking down write access.
